openapi: 3.0.0
info:
  title: EVER-Lab-OS API
  version: 1.0.0
  description: BSL-2対応研究施設管理システム API仕様
  contact:
    name: EVER-Lab Support
    email: support@ever-lab.io

servers:
  - url: https://asia-northeast1-{project-id}.cloudfunctions.net
    description: Cloud Functions
    variables:
      project-id:
        default: everlab-prod
        enum:
          - everlab-dev
          - everlab-stg
          - everlab-prod

tags:
  - name: Equipment
    description: 機器管理API
  - name: Reservations
    description: 予約管理API
  - name: Consumables
    description: 消耗品管理API
  - name: Users
    description: ユーザー管理API

paths:
  /api/equipment:
    get:
      tags: [Equipment]
      summary: 機器一覧取得
      operationId: getEquipment
      parameters:
        - name: category
          in: query
          schema:
            $ref: '#/components/schemas/EquipmentCategory'
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/EquipmentStatus'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Equipment'

components:
  schemas:
    Equipment:
      type: object
      required:
        - id
        - name
        - category
        - status
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          description: 機器名
        category:
          type: string
        status:
          type: string
    EquipmentCategory:
      type: string
      enum: [Microscopes, Centrifuges, Incubators]
    EquipmentStatus:
      type: string
      enum: [Available, InUse, Maintenance]
        
  securitySchemes:
    FirebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Firebase Authentication IDトークン
